package cmd

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"os/exec"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/LinkStateDev/linkstate-cli/internal/config"
	"github.com/LinkStateDev/linkstate-cli/internal/lesson"
	"github.com/LinkStateDev/linkstate-cli/internal/ui"
	"github.com/spf13/cobra"
)

var testCmd = &cobra.Command{
	Use:   "test",
	Short: "Run tests against your solution",
	RunE: func(cmd *cobra.Command, args []string) error {
		return runTests(false)
	},
}

// taskManifestEntry matches tasks.json format generated by the sync tool.
type taskManifestEntry struct {
	ID    int      `json:"id"`
	Slug  string   `json:"slug"`
	Title string   `json:"title"`
	Hints []string `json:"hints"`
}

// groupedResult holds one task's worth of test results.
type groupedResult struct {
	taskNum  int
	slug     string
	title    string
	passed   []testResult
	failed   []testResult
	skipped  []testResult
}

var (
	resultRe      = regexp.MustCompile(`^\s*--- (PASS|FAIL|SKIP):?\s*(.*?)(?:\s+\(\d+\.\d+s\))?\s*$`)
	runRe         = regexp.MustCompile(`^\s*=== RUN\s+(.*)$`)
	detailStripRe = regexp.MustCompile(`^\s*main_test\.go:\d+:\s*`)
	taskRe        = regexp.MustCompile(`^TestTask(\d+)_`)
)

type testResult struct {
	name    string
	failed  bool
	skipped bool
	details []string
}

func runTests(submitting bool) error {
	if _, err := os.Stat("main.go"); os.IsNotExist(err) {
		return errorWithHint("main.go not found in current directory", "run lst from a fetched lesson directory")
	}
	if _, err := os.Stat("test"); os.IsNotExist(err) {
		return errorWithHint("test binary not found", "fetch the lesson first: lst start <slug>")
	}

	// Remember this lesson as the last one the student worked on.
	saveLastLesson()
	if _, err := os.Stat("go.mod"); os.IsNotExist(err) {
		os.WriteFile("go.mod", []byte("module solution\n\ngo 1.21\n"), 0644)
	}

	cmd := exec.Command("./test", "-v")
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return err
	}
	if err := cmd.Start(); err != nil {
		return err
	}

	all := parseTestOutput(stdout)
	cmd.Wait()

	if len(all) == 0 {
		return errorWithHint(
			"code does not compile — check main.go for errors",
			"Fix compilation errors and run 'lst test' again",
		)
	}

	groups := groupByTask(all)
	groups = loadTaskTitles(groups)

	totalPass, totalFail, totalSkip := 0, 0, 0
	for i, g := range groups {
		if i > 0 {
			fmt.Println()
		}
		passCount := len(g.passed)
		failCount := len(g.failed)
		skipCount := len(g.skipped)
		totalPass += passCount
		totalFail += failCount
		totalSkip += skipCount

		status := ui.Success.Render("Done")
		statusColor := ui.Success
		if failCount > 0 || passCount == 0 {
			status = ui.Error.Render("Not Done")
			statusColor = ui.Error
		}

		displayName := g.title
		if displayName == "" {
			displayName = fmt.Sprintf("Task %d", g.taskNum)
		}
		fmt.Printf("%s %s: %s — %s\n",
			ui.Bold.Render("▸"),
			ui.Bold.Render(fmt.Sprintf("Task %d", g.taskNum)),
			ui.Bold.Render(displayName),
			status,
		)

		for _, r := range g.failed {
			fmt.Printf("  %s  %s\n",
				ui.Error.Render(ui.GlyphFail),
				ui.Bold.Render(humanName(r.name)),
			)
			if len(r.details) > 0 {
				for _, d := range r.details {
					fmt.Printf("    %s %s\n", ui.Muted.Render("┃"), statusColor.Render(d))
				}
			}
		}
		if failCount > 0 && g.slug != "" {
			fmt.Printf("  %s %s\n",
				ui.Hint.Render(ui.GlyphHint),
				ui.Hint.Render(fmt.Sprintf("Run: lst hint %s", g.slug)),
			)
		}
		for _, r := range g.skipped {
			fmt.Printf("  %s  %s\n",
				ui.Muted.Render("○"),
				ui.Muted.Render(humanName(r.name)),
			)
		}
		for _, r := range g.passed {
			fmt.Printf("  %s  %s\n",
				ui.Success.Render(ui.GlyphPass),
				humanName(r.name),
			)
		}

		if i < len(groups)-1 {
			time.Sleep(200 * time.Millisecond)
		}
	}

	fmt.Println()
	summary := fmt.Sprintf("%d passed", totalPass)
	if totalFail > 0 {
		summary += fmt.Sprintf(" · %d failed", totalFail)
	}
	if totalSkip > 0 {
		summary += fmt.Sprintf(" · %d skipped", totalSkip)
	}
	if totalFail == 0 && totalPass > 0 {
		fmt.Println(ui.SummaryPass.Render(summary))
		if !submitting {
			fmt.Println()
			fmt.Println("  " + ui.Muted.Render("All green. Run: ") + ui.Hint.Render("lst submit"))
		}
		return nil
	}
	fmt.Println(ui.SummaryFail.Render(summary))
	return fmt.Errorf("%d test(s) failed", totalFail)
}

func parseTestOutput(stdout io.Reader) []testResult {
	var (
		results       []testResult
		seen          = map[string]bool{}
		detailsByTest = map[string][]string{}
		currentTest   string
	)
	scanner := bufio.NewScanner(stdout)
	for scanner.Scan() {
		text := scanner.Text()

		if m := runRe.FindStringSubmatch(text); m != nil {
			currentTest = strings.TrimSpace(m[1])
			continue
		}

		if m := resultRe.FindStringSubmatch(text); m != nil {
			name := strings.TrimSpace(m[2])
			if name == "" || seen[name] {
				continue
			}
			seen[name] = true
			r := testResult{name: name, details: detailsByTest[name]}
			switch m[1] {
			case "FAIL":
				r.failed = true
			case "SKIP":
				r.skipped = true
			}
			results = append(results, r)
			continue
		}

		if strings.TrimSpace(text) == "FAIL" {
			continue
		}
		if strings.HasPrefix(strings.TrimSpace(text), "FAIL\t") ||
			strings.HasPrefix(strings.TrimSpace(text), "ok\t") ||
			strings.HasPrefix(strings.TrimSpace(text), "?\t") ||
			strings.Contains(text, "exit status") {
			continue
		}

		if currentTest != "" && strings.TrimSpace(text) != "" {
			clean := detailStripRe.ReplaceAllString(strings.TrimSpace(text), "")
			if clean != "" {
				detailsByTest[currentTest] = append(detailsByTest[currentTest], clean)
				for i := range results {
					if results[i].name == currentTest {
						results[i].details = detailsByTest[currentTest]
					}
				}
			}
		}
	}

	filtered := make([]testResult, 0, len(results))
	for _, r := range results {
		hasSub := false
		for _, other := range results {
			if other.name != r.name && strings.HasPrefix(other.name, r.name+"/") {
				hasSub = true
				break
			}
		}
		if hasSub && len(r.details) == 0 {
			continue
		}
		filtered = append(filtered, r)
	}
	return filtered
}

func groupByTask(results []testResult) []groupedResult {
	groups := map[int]*groupedResult{}
	for _, r := range results {
		num := extractTaskNum(r.name)
		g, ok := groups[num]
		if !ok {
			g = &groupedResult{taskNum: num}
			groups[num] = g
		}
		if r.failed {
			g.failed = append(g.failed, r)
		} else if r.skipped {
			g.skipped = append(g.skipped, r)
		} else {
			g.passed = append(g.passed, r)
		}
	}
	var out []groupedResult
	for _, g := range groups {
		out = append(out, *g)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].taskNum < out[j].taskNum })
	return out
}

func extractTaskNum(name string) int {
	if m := taskRe.FindStringSubmatch(name); m != nil {
		var n int
		fmt.Sscanf(m[1], "%d", &n)
		return n
	}
	return 0
}

func loadTaskTitles(groups []groupedResult) []groupedResult {
	data, err := os.ReadFile("tasks.json")
	if err != nil {
		return groups
	}
	var tasks []taskManifestEntry
	if err := json.Unmarshal(data, &tasks); err != nil {
		return groups
	}
	for i := range groups {
		n := groups[i].taskNum - 1
		if n >= 0 && n < len(tasks) {
			groups[i].title = tasks[n].Title
			groups[i].slug = tasks[n].Slug
		}
	}
	return groups
}

var expectedGotRe = regexp.MustCompile(`(?i)^\s*(expected|got|want|have|actual)\b[\s:=-]*(.*)$`)

func formatDetails(lines []string) string {
	out := make([]string, 0, len(lines))
	for _, l := range lines {
		l = cleanDetail(l)
		if l == "" {
			continue
		}
		if m := expectedGotRe.FindStringSubmatch(l); m != nil {
			label := strings.ToLower(m[1])
			value := strings.TrimSpace(m[2])
			switch label {
			case "got", "actual", "have":
				out = append(out, fmt.Sprintf("%s  %s", ui.Error.Render(pad(label)), value))
			default:
				out = append(out, fmt.Sprintf("%s  %s", ui.Hint.Render(pad(label)), value))
			}
			continue
		}
		out = append(out, l)
	}
	return strings.Join(out, "\n")
}

func pad(s string) string {
	const w = 8
	if len(s) >= w {
		return s
	}
	return s + strings.Repeat(" ", w-len(s))
}

func humanName(name string) string {
	if idx := strings.LastIndex(name, "/"); idx > 0 {
		name = name[idx+1:]
	}
	name = strings.ReplaceAll(name, "_", " ")
	name = strings.TrimPrefix(name, "Test")
	name = strings.TrimPrefix(name, "Task1 ")
	name = strings.TrimPrefix(name, "Task2 ")
	name = strings.TrimPrefix(name, "Task3 ")
	name = strings.TrimPrefix(name, "Task4 ")
	name = strings.TrimPrefix(name, "Task5 ")
	return name
}

func cleanDetail(d string) string {
	d = strings.ReplaceAll(d, "\\n", "")
	return d
}

func saveLastLesson() {
	meta, err := lesson.LoadMeta()
	if err != nil || meta.Slug == "" {
		return
	}
	if cfg.LastLessonSlug == meta.Slug && cfg.LastTrackSlug == meta.TrackSlug {
		return
	}
	cfg.LastTrackSlug = meta.TrackSlug
	cfg.LastLessonSlug = meta.Slug
	cfg.LastLessonTitle = meta.Title
	_ = config.Save(cfg)
}

func init() { rootCmd.AddCommand(testCmd) }
